name: Health Check

on:
  push:
    branches:
      - main

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v4
        with:
          url: https://fcs-pokedex.fly.dev/health
